name: build-container
run-name: ${{ github.actor }} is building container
on: 
  # Trigger the action manually from the UI
  workflow_dispatch:
  # Trigger the action when a version tag is pushed
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+' # Push events to matching numeric semver tags, i.e., 1.0.0, 20.15.10

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_BACKEND: backend
  IMAGE_NAME_FRONTEND: frontend

jobs:
  build_docker_images:
    # Job name that shows in the GitHub Website:
    name: Build Docker Images
    # Runner to use:
    runs-on: ub